@startuml UseCase
left to right direction
rectangle K-Anode-Received-Assistant {
    usecase "Receive K-Anode" as receive
    usecase "Verify Received" as verify
    usecase "Delivery before receiving" as delivery
    usecase "View Record" as view
    usecase "Export Data" as export
    usecase "Import Balance from WMS" as import
}
User --> receive

receive ..> verify : <<Include>>
verify ..> import : <<Include>>

verify <.. delivery : <<Extend>>

User --> view
User --> export
@enduml