@startuml Class

class KAnode{
    -PartNo : string
    -LotNo : string
    -Quantity : int
    --
    +KAnode(partNo : string, lotNo : string, quantity : int)

    +SetPartNo(partNo : string) : void
    +GetPartNo() : string
    +SetLotNo(lotNo : string) : void
    +GetLotNo() : string
    +SetQuantity(quantity : int) : void
    +GetQuantity() : int

    -CheckPatternOfPartNo(partNo : string) : bool
    -CheckParternOfLotNo(lotNo : string) : bool
    ==Pattern with Regex==
    PartNo :
    LotNo :
}

class Invoice{
    -InvoiceNo : string
    -Quantity : int
    -DeliveryDate : Date
    -KAnodeLists : ArrayList

    +Invoice()
    +Invoice(invoiceNo : string)
    +Invoice(invoiceNo : string, quantity : int)
    +Invoice(invoiceNo : string, quantity : int, deliveryDate : Date)

    +SetInvoice(invoiceNo : string) : void
    +GetInvoice() : string
    +SetQuantity(quantity : int) : void
    +GetQuantity() : int
    +SetDeliveryDate(deliveryDate : Date) : void
    +GetDeliveryDate() : Date
    +SetKAondeLists(kAnodeLists : ArrayList) : void
    +GetKAnodeLists() : ArrayList
}
Invoice "1" *-- "1..*" KAnode

class Location{
    -LocationID : int
    -LocationName : string
}
Location "1" <-- "0..*" KAnode : PutAway

enum ORIGIN{
    AIR
    TOKIN
}
class Receive{
    -ReceiveId : int
    -ReceiveToOracleDate : DateTime
    +Origin : ORIGIN

    
}
'ENUM of Receive'
ORIGIN --* Receive
'Association of Receive'
(KAnode, Location) .. Receive

class Verify

class ImportWMS

class ViewData

class Export



@enduml